name: build

on:
  pull_request:
    paths:
      - "**/*.java"
  push:
    paths:
      - "**/*.java"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build
        run: chmod +x gradlew && ./gradlew build -x test --stacktrace

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
